name: Go

on:
  pull_request: {}
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".github/workflows/go.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Go format
        run: make go-fmt-check

      - name: Go vet
        run: make go-vet

      - name: Go test
        run: make go-test

      - name: Go build
        run: make go-build
