name: Go

on:
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go.yml"
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Go test
        run: go test ./...

      - name: Go vet
        run: go vet ./...
